### ISSUE TITLE
Invoke-UpdateAzureBlobPKIStorage.ps1

### ISSUE THREAD

**Issue by hansdampf01** [dstreefkerk/PowerShell#1]
Hey Daniel,

It seems the Script to Upload the ICA to Azure doesn't work anymore - is there a remote chance you will take a look? 

Cheers
George from Germany

**Comment by dstreefkerk** [comment]
Hi George, unfortunately I'm not in a position where I could test and update the script anymore without setting up a full new Azure AD tenant and lab environment.

Can you give some more detail about where it's erroring out? Perhaps I could assist that way.

Regards,
Daniel
