### ISSUE TITLE
mimecast

### ISSUE THREAD

**Issue by itguysocal** [dstreefkerk/PowerShell#4]
Hi Daniel,
Can you parse the MX record contents for us-smtp-inbound-1.mimecast.com or
us-smtp-inbound-2.mimecast.com so that the MX provider is reported as Mimecast (US) and then "de-smtp-inbound-2.mimecast.com" as Mimecast (Germany)

**Comment by dstreefkerk** [comment]
Yes, I’ll add those as soon as I can. Or feel free to do it yourself and submit a patch.
